[package]
edition = "2021"
name = "json-log-printer"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
owo-colors = "3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
